<?php
$GLOBALS = array(
		'_POST'=>array(),
		'_GET'=>array(),
		'_SESSION'=>array(),
		'_INTIN'=>array(
				'MOD'=>$_INTIN['MOD'],
				NULL=>NULL
		),
		'_INTIN'=>$_INTIN,
		'_SESSIONthread'=>array(),
		'_QUERY'=>array(),
		'_SERVER'=>array(
				'DOCUMENT_ROOT'=>$_SERVER['DOCUMENT_ROOT'],
				null=>null
		),
		'_ENV'=>array(),
		'_COOKIE'=>'',
		'_FILES'=>$_FILES,
		'_REQUEST'=>array(),
		NULL=>NULL
);
?>